name: Proyecto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ========================
  # 1) CI: Lint + Unit Tests
  # ========================
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Lint del Código
        run: npm exec eslint .

      - name: Ejecutar Pruebas con Cobertura
        run: npm test -- --coverage --ci

      - name: Subir Reporte de Cobertura
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

  # ====================================
  # 2) Performance Tests con k6 (ramp, spike, soak)
  # ====================================
  performance:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'perf')

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Instalar k6
        run: |
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6 -y

      - name: Ejecutar pruebas k6
        run: |
          mkdir -p reports
          k6 run --summary-export=reports/summary.json backend/k6-test/auth-load-test.js
          k6 run --summary-export=reports/spike.json backend/k6-test/crud-operations.js
          k6 run --summary-export=reports/soak.json backend/k6-test/health-check.js
          k6 run --summary-export=reports/soak.json backend/k6-test/quick-dev-test.js
          k6 run --summary-export=reports/soak.json backend/k6-test/simple-debug-test.js
          k6 run --summary-export=reports/soak.json backend/k6-test/spike-test.js
          k6 run --summary-export=reports/soak.json backend/k6-test/stress-test.js
          k6 run --summary-export=reports/soak.json backend/k6-test/sustained-load-test.js

      - name: Subir reportes de k6
        uses: actions/upload-artifact@v4
        with:
          name: k6-reports
          path: reports

  # ========================
  # 3) Deploy
  # ========================
  deploy:
    runs-on: ubuntu-latest
    needs: [ci, performance]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Ejemplo: despliegue en Vercel (cámbialo según tu caso)
      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Desplegar en Vercel
        run: vercel --token=$VERCEL_TOKEN --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}


