name: Proyecto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 1) CI: Lint + Unit Tests
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Lint del Código
        run: npm exec eslint .

      - name: Ejecutar Pruebas con Cobertura
        run: npm test -- --coverage --ci

      - name: Subir Reporte de Cobertura
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

  # 2) Performance Tests con k6 
  performance:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'perf')

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Instalar k6
        run: |
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6 -y


      - name: Instalar dependencias backend
        run: |
          cd backend
          npm install

      - name: Ejecutar pruebas k6 de auth-load-test
        run: |
          mkdir -p reports
          k6 run --summary-export=reports/auth-summary.json backend/k6-tests/auth-load-test.js

      - name: Ejecutar pruebas k6 de crud operations
        run: |
          mkdir -p reports
          k6 run --summary-export=reports/crud-summary.json backend/k6-tests/crud-operations.js


      - name: Ejecutar pruebas k6 de health checks
        run: |
          mkdir -p reports
          k6 run --summary-export=reports/health-summary.json backend/k6-tests/health-check.js


      - name: Ejecutar pruebas k6 de simple-debug-test
        run: |
          mkdir -p reports
          k6 run --summary-export=reports/simple-debug-summary.json backend/k6-tests/simple-debug-test.js

      - name: Ejecutar pruebas k6 de spike-test
        run: |
          mkdir -p reports
          k6 run --summary-export=reports/spike-summary.json backend/k6-tests/spike-test.js

      - name: Ejecutar pruebas k6 de stress-test
        run: |
          mkdir -p reports
          k6 run --summary-export=reports/stress-summary.json backend/k6-tests/stress-test.js

      - name: Ejecutar pruebas k6 de sustained-load-test
        run: |
          mkdir -p reports
          k6 run --summary-export=reports/sustained-load-summary.json backend/k6-tests/sustained-load-test.js

      - name: Subir reportes de k6
        uses: actions/upload-artifact@v4
        with:
          name: k6-reports
          path: reports

  # 3) Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: [ci, performance]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Desplegar en Firebase
        run: echo "https://proyectopruebas-60f7f.web.app/"


